### ISSUE TITLE
Compatibility with the newest Kinetic JS

### ISSUE THREAD

**Issue by 14422** [evktalo/kiigame#4]
The game was implemented with Kinetic JS version 4.7.1, but with quick test 4.7.3 didn't work with the game and no debugging was done due to lack of time.

At the moment there is already version 5.0.0 of Kinetic JS so debugging the possible small or big incompatibility issues would be required.

The game has quite large amount of CPU usage especially during animations so newer optimized versions would be welcome.

**Comment by evktalo** [comment]
5.1.0 is the last version from the original maintainer. Test against that.

**Comment by evktalo** [comment]
Consider moving over to https://github.com/konvajs/konva which is based on KineticJS.

**Comment by evktalo** [comment]
4.7.4 seems to work fine with some changes. Pushing branch soon.

**Comment by evktalo** [comment]
Pushed here: https://github.com/evktalo/kiigame/tree/kineticJS-update-4.7.4

I still want to try to get 5.1.0 working. With a little of tweaking, splash screen, menu and intro work 100%, but most of the actual playing screen is just white.

**Comment by evktalo** [comment]
5.1.0 update seems to be working. Pushing branch soon.
